namespace Kula.Lexing;

/// <summary>
/// The lexer is responsible for taking a string of text and breaking it up into a series of tokens.
/// </summary>
internal class Lexer
{
    /// <summary>
    /// The output <see cref="Token"/> which are generated by the lexer.
    /// </summary>
    internal List<Token> Tokens { get; }

    internal Lexer()
    {
        Tokens = new List<Token>();
    }

    /// <summary>
    /// Tokenizes the given source code and converts it into a series of tokens. Theses tokens get
    /// appended to the <see cref="Tokens"/> list.
    /// </summary>
    /// <param name="sourceCode">The Kula source code to tokenize.</param>
    internal void Tokenize(string sourceCode)
    {
        
    }
}